//! SparkOS Modern 16x16 HD Icon Theme Package (`src/icons.rs`)
//!
//! Provides pixel-perfect, anti-aliased RGBA icon assets for all desktop apps,
//! network interfaces (Ethernet, Wi-Fi), system status indicators, and shell widgets.

use crate::app_registry::AppIcon;

pub const ICON_SIZE: usize = 16;
pub const T: u32 = 0x00000000; // Transparent

// ---------------------------------------------------------------------------
// Modern Color Tokens
// ---------------------------------------------------------------------------

const C_LOGO_CORE: u32 = 0x0038BDF8; // Sky 400
const C_LOGO_DARK: u32 = 0x000284C7; // Sky 600
const C_LOGO_LGT: u32  = 0x00BAE6FD; // Sky 200
const C_LOGO_WHT: u32  = 0x00F0F9FF; // Sky 50

const C_TERM_BG: u32   = 0x001E293B; // Slate 800
const C_TERM_BRD: u32  = 0x00334155; // Slate 700
const C_TERM_GRN: u32  = 0x0010B981; // Emerald 500
const C_TERM_WHT: u32  = 0x00F8FAFC; // Slate 50

const C_FILE_FLDR: u32 = 0x00F59E0B; // Amber 500
const C_FILE_LGT: u32  = 0x00FCD34D; // Amber 300
const C_FILE_DRK: u32  = 0x00D97706; // Amber 600

const C_EDIT_PPR: u32  = 0x00F8FAFC; // White
const C_EDIT_LIN: u32  = 0x0094A3B8; // Slate 400
const C_EDIT_ACC: u32  = 0x00EC4899; // Pink 500
const C_EDIT_DRK: u32  = 0x00CBD5E1; // Slate 300

const C_TASK_BG: u32   = 0x000F172A; // Deep Navy
const C_TASK_GRN: u32  = 0x0034D399; // Emerald 400

const C_SETT_MTL: u32  = 0x0094A3B8; // Slate 400
const C_SETT_DRK: u32  = 0x00475569; // Slate 600
const C_SETT_LGT: u32  = 0x00E2E8F0; // Slate 200

const C_GLOB_BLU: u32  = 0x003B82F6; // Blue 500
const C_GLOB_LGT: u32  = 0x0060A5FA; // Blue 400
const C_GLOB_WHT: u32  = 0x00E0F2FE; // Sky 100
const C_GLOB_DRK: u32  = 0x001D4ED8; // Blue 700

const C_NET_GRN: u32   = 0x0010B981; // Emerald 500 (Active Link)
const C_NET_CYN: u32   = 0x0006B6D4; // Cyan 500
const C_NET_GRY: u32   = 0x0064748B; // Slate 500 (Disconnected)
const C_NET_RED: u32   = 0x00EF4444; // Red 500 (Error / Off)

// 1. SparkOS Sparkle Logo (16x16)
pub const ICON_LOGO_16: [u32; 256] = [
    T, T, T, T, T, T, T, C_LOGO_CORE, C_LOGO_CORE, T, T, T, T, T, T, T,
    T, T, T, T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_LGT, C_LOGO_CORE, T, T, T, T, T, T,
    T, T, T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T, T, T, T,
    T, T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T, T, T,
    T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T, T,
    T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_DARK, C_LOGO_DARK, C_LOGO_DARK, C_LOGO_DARK, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T,
    T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_DARK, C_LOGO_CORE, C_LOGO_CORE, C_LOGO_CORE, C_LOGO_CORE, C_LOGO_DARK, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T,
    C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_DARK, C_LOGO_CORE, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_CORE, C_LOGO_DARK, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE,
    C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_DARK, C_LOGO_CORE, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_CORE, C_LOGO_DARK, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE,
    T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_DARK, C_LOGO_CORE, C_LOGO_CORE, C_LOGO_CORE, C_LOGO_CORE, C_LOGO_DARK, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T,
    T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_DARK, C_LOGO_DARK, C_LOGO_DARK, C_LOGO_DARK, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T,
    T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T, T,
    T, T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T, T, T,
    T, T, T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_LGT, C_LOGO_CORE, T, T, T, T, T,
    T, T, T, T, T, T, C_LOGO_CORE, C_LOGO_LGT, C_LOGO_LGT, C_LOGO_CORE, T, T, T, T, T, T,
    T, T, T, T, T, T, T, C_LOGO_CORE, C_LOGO_CORE, T, T, T, T, T, T, T,
];

// 2. Terminal Console Icon (16x16)
pub const ICON_TERMINAL_16: [u32; 256] = [
    T, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, T,
    C_TERM_BRD, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, T, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, C_TERM_GRN, T, T, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, T, T, T, T, C_TERM_WHT, C_TERM_WHT, C_TERM_WHT, C_TERM_WHT, C_TERM_WHT, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, T, T, T, T, C_TERM_WHT, C_TERM_WHT, C_TERM_WHT, C_TERM_WHT, C_TERM_WHT, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, T, T, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, T, T, T, T, T, T, T, T, T, T, T, T, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BRD,
    C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD, C_TERM_BRD,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

// 3. Files / Folder Icon (16x16)
pub const ICON_FILES_16: [u32; 256] = [
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, T, T, T, T, T, T, T, T, T, T,
    C_FILE_DRK, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, T, T, T,
    C_FILE_DRK, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_DRK, T, T,
    C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_LGT, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_FLDR, C_FILE_LGT, C_FILE_DRK, T,
    C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, C_FILE_DRK, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

// 4. Text Editor / Document Icon (16x16)
pub const ICON_EDITOR_16: [u32; 256] = [
    T, T, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, T, T, T, T, T, T,
    T, C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, C_EDIT_DRK, T, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_ACC, C_EDIT_ACC, C_EDIT_ACC, C_EDIT_ACC, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_LIN, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    C_EDIT_DRK, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_PPR, C_EDIT_DRK, T, T, T,
    T, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, C_EDIT_DRK, T, T, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

// 5. Task Manager / Activity Pulse Icon (16x16)
pub const ICON_TASKMGR_16: [u32; 256] = [
    T, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, T,
    C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, T, T, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, C_TASK_GRN, T, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, C_TASK_GRN, C_TASK_GRN, T, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, C_TASK_GRN, C_TASK_GRN, T, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, C_TASK_GRN, T, C_TASK_GRN, T, T, C_TASK_GRN, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, C_TASK_GRN, C_TASK_GRN, C_TASK_GRN, C_TASK_GRN, T, C_TASK_GRN, T, C_TASK_GRN, C_TASK_GRN, C_TASK_GRN, C_TASK_GRN, C_TASK_GRN, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, C_TASK_GRN, C_TASK_GRN, T, C_TASK_GRN, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, C_TASK_GRN, C_TASK_GRN, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, T, C_TASK_GRN, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, T, T, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, T, T, T, T, T, T, T, T, T, T, T, T, C_TASK_BG, C_TASK_BG,
    C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG,
    T, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, C_TASK_BG, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

// 6. Settings / Gear Icon (16x16)
pub const ICON_SETTINGS_16: [u32; 256] = [
    T, T, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T, T, T, T,
    T, T, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, T, T, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, T, T, C_SETT_MTL, C_SETT_DRK, T,
    T, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, T,
    T, T, C_SETT_DRK, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, C_SETT_DRK, T, T,
    T, T, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, T, T,
    C_SETT_DRK, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, C_SETT_DRK,
    C_SETT_MTL, C_SETT_MTL, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, T, T, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_MTL, C_SETT_MTL,
    C_SETT_MTL, C_SETT_MTL, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, T, T, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_MTL, C_SETT_MTL,
    C_SETT_DRK, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, C_SETT_DRK,
    T, T, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, T, T,
    T, T, C_SETT_DRK, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_DRK, C_SETT_DRK, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, C_SETT_DRK, T, T,
    T, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_MTL, C_SETT_MTL, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, T,
    T, C_SETT_DRK, C_SETT_MTL, T, T, C_SETT_DRK, C_SETT_LGT, C_SETT_LGT, C_SETT_LGT, C_SETT_LGT, C_SETT_DRK, T, T, C_SETT_MTL, C_SETT_DRK, T,
    T, T, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T, T, T, T,
    T, T, T, T, T, T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T, T, T, T,
];

// 7. Web Browser / Globe Icon (16x16)
pub const ICON_BROWSER_16: [u32; 256] = [
    T, T, T, T, T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_DRK, T, T, T, T, T,
    T, T, T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_DRK, T, T, T, T,
    T, T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_DRK, T, T, T,
    T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_DRK, T, T,
    T, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, T, T,
    C_GLOB_DRK, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_DRK, T,
    C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU,
    C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU,
    C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU,
    C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU,
    C_GLOB_DRK, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_DRK, T,
    T, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, T, T,
    T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_DRK, T, T,
    T, T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_WHT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_DRK, T, T, T,
    T, T, T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_WHT, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_LGT, C_GLOB_BLU, C_GLOB_DRK, T, T, T, T,
    T, T, T, T, T, C_GLOB_DRK, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_BLU, C_GLOB_DRK, T, T, T, T, T,
];

// 8. Ethernet RJ45 Connection Icon (16x16)
pub const ICON_ETH_16: [u32; 256] = [
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, T, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, T, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_NET_GRN, C_NET_GRN, C_SETT_MTL, C_NET_GRN, C_NET_GRN, C_SETT_MTL, C_NET_GRN, C_NET_GRN, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_NET_GRN, C_NET_GRN, C_SETT_MTL, C_NET_GRN, C_NET_GRN, C_SETT_MTL, C_NET_GRN, C_NET_GRN, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_SETT_DRK, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_MTL, C_SETT_DRK, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_TERM_BG, C_SETT_DRK, C_SETT_MTL, C_SETT_MTL, C_SETT_DRK, T, T, T,
    T, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, C_SETT_DRK, T, T, T,
    T, T, T, T, T, C_NET_GRN, C_NET_GRN, C_NET_GRN, T, T, T, T, T, T, T, T,
    T, T, T, T, T, C_NET_GRN, C_NET_GRN, C_NET_GRN, T, T, T, T, T, T, T, T,
    T, T, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, T, T, T,
    T, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, C_NET_GRN, T, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

// 9. Modern Wi-Fi Wave Broadcast Icon (16x16)
pub const ICON_WIFI_16: [u32; 256] = [
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, T, T, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, T, T, T,
    T, T, C_NET_CYN, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_NET_CYN, T, T,
    T, C_NET_CYN, C_LOGO_WHT, T, T, T, T, T, T, T, T, T, T, C_LOGO_WHT, C_NET_CYN, T,
    T, T, T, T, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, T, T, T, T,
    T, T, T, C_NET_CYN, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_NET_CYN, T, T, T,
    T, T, C_NET_CYN, C_LOGO_WHT, T, T, T, T, T, T, T, T, C_LOGO_WHT, C_NET_CYN, T, T,
    T, T, T, T, T, T, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, T, T, T, T, T, T,
    T, T, T, T, T, C_NET_CYN, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_LOGO_WHT, C_NET_CYN, T, T, T, T, T,
    T, T, T, T, C_NET_CYN, C_LOGO_WHT, T, T, T, T, C_LOGO_WHT, C_NET_CYN, T, T, T, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, T, T, T, T, T, C_NET_CYN, C_NET_CYN, C_NET_CYN, C_NET_CYN, T, T, T, T, T, T,
    T, T, T, T, T, T, C_NET_CYN, C_LOGO_WHT, C_LOGO_WHT, C_NET_CYN, T, T, T, T, T, T,
    T, T, T, T, T, T, C_NET_CYN, C_LOGO_WHT, C_LOGO_WHT, C_NET_CYN, T, T, T, T, T, T,
    T, T, T, T, T, T, T, C_NET_CYN, C_NET_CYN, T, T, T, T, T, T, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

// 10. Disconnected Network (16x16)
pub const ICON_NET_DISCONNECTED_16: [u32; 256] = [
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
    T, C_NET_RED, T, T, T, T, T, T, T, T, T, T, T, T, C_NET_RED, T,
    T, T, C_NET_RED, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_RED, T, T,
    T, T, C_NET_GRY, C_NET_RED, T, T, T, T, T, T, T, T, C_NET_RED, C_NET_GRY, T, T,
    T, T, C_NET_GRY, T, C_NET_RED, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_RED, T, C_NET_GRY, T, T,
    T, T, C_NET_GRY, T, T, C_NET_RED, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_RED, T, T, C_NET_GRY, T, T,
    T, T, C_NET_GRY, T, T, T, C_NET_RED, T, T, C_NET_RED, T, T, T, C_NET_GRY, T, T,
    T, T, T, T, T, T, T, C_NET_RED, C_NET_RED, T, T, T, T, T, T, T,
    T, T, T, T, T, T, T, C_NET_RED, C_NET_RED, T, T, T, T, T, T, T,
    T, T, C_NET_GRY, T, T, T, C_NET_RED, T, T, C_NET_RED, T, T, T, C_NET_GRY, T, T,
    T, T, C_NET_GRY, T, T, C_NET_RED, T, T, T, T, C_NET_RED, T, T, C_NET_GRY, T, T,
    T, T, C_NET_GRY, T, C_NET_RED, T, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, T, C_NET_RED, T, C_NET_GRY, T, T,
    T, T, C_NET_GRY, C_NET_RED, T, T, T, T, T, T, T, T, C_NET_RED, C_NET_GRY, T, T,
    T, T, C_NET_RED, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_GRY, C_NET_RED, T, T,
    T, C_NET_RED, T, T, T, T, T, T, T, T, T, T, T, T, C_NET_RED, T,
    T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T,
];

/// Renders a high-definition 16x16 icon directly onto the backbuffer with clipping support
pub fn render_icon_16(px: u16, py: u16, icon: AppIcon, _bg_fallback: u32) {
    let data = match icon {
        AppIcon::Logo => &ICON_LOGO_16,
        AppIcon::Terminal => &ICON_TERMINAL_16,
        AppIcon::Files => &ICON_FILES_16,
        AppIcon::Editor => &ICON_EDITOR_16,
        AppIcon::TaskMgr => &ICON_TASKMGR_16,
        AppIcon::SysMon => &ICON_TASKMGR_16,
        AppIcon::Settings => &ICON_SETTINGS_16,
        AppIcon::Browser => &ICON_BROWSER_16,
        _ => &ICON_LOGO_16,
    };

    render_raw_icon_16(px, py, data);
}

/// Renders network status icon (Ethernet / Wi-Fi / Disconnected)
pub fn render_network_icon(px: u16, py: u16, is_wifi: bool, connected: bool) {
    let data = if !connected {
        &ICON_NET_DISCONNECTED_16
    } else if is_wifi {
        &ICON_WIFI_16
    } else {
        &ICON_ETH_16
    };

    render_raw_icon_16(px, py, data);
}

/// Core renderer with strict clipping and backbuffer boundary clamping
pub fn render_raw_icon_16(px: u16, py: u16, data: &[u32; 256]) {
    let sw = unsafe { crate::gui::VESA.width };
    let sh = unsafe { crate::gui::VESA.height };
    let backbuffer = unsafe { crate::gui::BACKBUFFER };

    if backbuffer.is_null() { return; }

    for row in 0..16u16 {
        let cur_y = py + row;
        if cur_y >= sh { break; }
        for col in 0..16u16 {
            let cur_x = px + col;
            if cur_x >= sw { break; }

            // Clip Rect Check
            if let Some((cx, cy, cw, ch)) = unsafe { crate::gui::CLIP_RECT } {
                if cur_x < cx || cur_x >= cx + cw || cur_y < cy || cur_y >= cy + ch {
                    continue;
                }
            }

            let pixel_color = data[(row as usize) * 16 + (col as usize)];
            if pixel_color != T {
                let offset = (cur_y as usize) * (sw as usize) + (cur_x as usize);
                unsafe {
                    core::ptr::write_volatile(backbuffer.add(offset), pixel_color);
                }
            }
        }
    }
}
